---
- include: "{{ common_tasks }}/wine-install.yml"
  vars:
    package:
      name: acemoney
      path: "{{ ansible_env.HOME }}/.wine/drive_c/Program Files (x86)/AceMoney/AceMoney.exe"
# here I download not the latest version, as there is a know issue with registration using the latest version,
# so have to download this one, register, and then upgrade to the latest version manually
      url: http://cdn.mechcad.net/downloads/AceMoneySetup.exe

