---
- hosts: localhost
  vars:
    common_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/common/tasks"
  roles:
    - common
    - { role: gnome, tags: ["gnome"] }
    - { role: packages, tags: ["packages"] }
    - { role: system, tags: ["system"] }
    - { role: media, tags: ["media"] }
    - { role: productivity, tags: ["productivity"] }
    - { role: dev, tags: ["dev"] }
  tasks:
    - name: debug vars
      debug:
        var: inventory_dir
      tags:
      - debug       
