---
- include: "{{ common_tasks }}/apt-install.yml"
  vars:
    package:
      name: google-chrome-stable    
      key: https://dl-ssl.google.com/linux/linux_signing_key.pub   
      repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"

- name: remove google chrome repo as /etc/cron.daily/google-chrome will create the one anyway with the same path and apt-get update will warn about duplicate entries found
  become: yes
  file: path=/etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list state=absent
  notify: update packages cache      
