---
- name: install libreoffice
  become: yes
  apt: name=libreoffice state=latest

- name: download ru dictionary extension
  get_url: url=https://extensions.libreoffice.org/extensions/russian-spellcheck-dictionary.-based-on-works-of-aot-group/0-4.3/@@download/file/dict_ru_ru-aot-0.4.3.oxt dest=/tmp/

- name: install ru dictionary extension      
  become: yes
  command: unopkg add --shared /tmp/dict_ru_ru-aot-0.4.3.oxt    
  register: ru_dict_ext_installed    
  ignore_errors: True    
  changed_when: ru_dict_ext_installed.rc == 0
