---
- name: install screencast related packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - byzanz  
    - imagemagick
    - mplayer
    - gtk-recordmydesktop
    - gifsicle
    - kazam  
    - vokoscreen  
    - xdotool  

