---
- name: add chrome signature key
  become: yes
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: add chrome repository
  become: yes
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" update_cache=yes state=present

- name: install chrome
  become: yes
  apt: name=google-chrome-stable state=present

- name: remove google chrome repo as /etc/cron.daily/google-chrome will create the one anyway with the same path and apt-get update will warn about duplicate entries found
  become: yes
  file: path=/etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list state=absent
  notify: update packages cache      

