---
- name: collect git config --global user properties
  command: git config --global --get user.name
  register: global_git_user_name
  ignore_errors: True
- command: git config --global --get user.email
  register: global_git_user_email
  ignore_errors: True

- name: set git user.name property
  command:  git config --global user.name "{{ git_user_name }}"
  when: global_git_user_name.stdout != git_user_name

- name: set git user.email property
  command: git config --global user.email {{ git_user_email }}
  when: global_git_user_email.stdout != git_user_email

- debug: msg="git global user.name is {{ global_git_user_name.stdout }} and var is {{ git_user_name }}"
- debug: msg="git global user.email is {{ global_git_user_email.stdout }} and var is {{ git_user_email }}"

