---
- include: apt.yml
- include: packages.yml tags=packages
- include: deb-packages.yml tags=deb-packages
- include: git-config.yml tags=git
- include: alternatives.yml
- include: dropbox.yml
- include: track-os-config.yml
- include: jdk.yml tags=jdk
- include: go.yml tags=dev
- include: atom.yml tags=dev,atom
