---
- name: enable contrib and non-free packages
  become: yes
  template: src=contrib-non-free.list dest=/etc/apt/sources.list.d/contrib-non-free.list

- name: update packages cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: upgrade dist
  become: yes
  apt: upgrade=dist

- name: install core packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - mc
    - vim
    - terminator
    - tilda
    - firmware-iwlwifi
    - git
    - chromium
    - tmux
    - keepassx

- name: install extra packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - calibre
    - wget
    - curl

- name: collect git config --global user properties
  command: git config --global --get user.name
  register: global_git_user_name
  ignore_errors: True
- command: git config --global --get user.email
  register: global_git_user_email
  ignore_errors: True

- name: set git user.name property
  command:  git config --global user.name "{{ git_user_name }}"
  when: global_git_user_name.stdout != git_user_name

- name: set git user.email property
  command: git config --global user.email {{ git_user_email }}
  when: global_git_user_email.stdout != git_user_email

- debug: msg="git global user.name is {{ global_git_user_name.stdout }} and var is {{ git_user_name }}"
- debug: msg="git global user.email is {{ global_git_user_email.stdout }} and var is {{ git_user_email }}"

- name: set main editor to vim
  become: yes
  alternatives: name=editor path=/usr/bin/vim.basic

- name: install dropbox
  shell: cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
  args: 
    creates: ~/.dropbox-dist

- name: init git for OS config directories (home)
  shell: cd {{ item }} && git init && git add . && git commit -m "Initial commit"
  args:
    creates: "{{ item }}/.git"
  with_items:
    - ~/.config
    - ~/.gconf
    - ~/.local

- name: init git for OS config directories (non home)
  become: yes
  shell: cd {{ item }} && git init && git add . && git commit -m "Initial commit"
  args:
    creates: "{{ item }}/.git"
  with_items:
    - /etc
    - /usr/share
    - /boot/grub

- name: install Oracle JDK 1.8
  become: yes
  shell: 'wget -O - --quiet --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/{{ jdk_archive }} | tar -C /usr/lib/jvm -xzf -'
  args:
    creates: /usr/lib/jvm/jdk{{ jdk_version }}
