---
- name: install core packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - mc
    - vim
    - terminator
    - tilda
    - firmware-iwlwifi
    - git
    - chromium
    - tmux
    - keepassx

- name: install extra packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - calibre
    - wget
    - curl
    - tree
    - meld
