---
- name: install core packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - mc
    - vim
    - vim-gtk
    - terminator
    - tilda
    - firmware-iwlwifi
    - git
    - chromium
    - tmux
    - keepassx
    - ttf-mscorefonts-installer

- name: install extra packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - calibre
    - wget
    - curl
    - tree
    - meld
    - zip
    - apt-transport-https # necessary for slack
    - xclip
    - xsel
    - python-gpgme # recommended for dropbox
