---
- name: download and unpack
  shell: wget -O - {{ item.url }} | tar -C /usr/local -xzf -
  args:
    creates: /usr/local/{{ item.name }}
  with_items:
      - { url: "http://ftp.tudelft.nl/apache//jmeter/binaries/apache-jmeter-2.13.tgz", name: "apache-jmeter-2.13" }      
