---
- name: chmod GOROOT
  become: yes
  file: owner={{ ansible_env.USER }} group={{ ansible_env.USER }} path=/usr/local/go{{ go_version }} recurse=yes state=directory

- name: unlink GOROOT
  become: yes 
  file: path=/usr/local/go state=absent

- name: link GOROOT
  become: yes
  file: src=/usr/local/go{{ go_version }} dest=/usr/local/go state=link
