---
- name: create symlink to core dot files
  file: src={{ role_path }}/files/{{ item }} dest={{ ansible_env.HOME }}/{{ item }} force=yes state=link
  with_items:
    - .tmux.conf
    - .profile 
    - .gitignore
    - .vimrc
    - .stalonetrayrc
    - .bash_aliases  
    - .gradle/gradle.properties
    - .lein/profiles.clj  

- name: assemble all bashrc fragments
  assemble: src={{ role_path }}/files/.bashrc.d dest={{ ansible_env.HOME }}/.bashrc.assemble delimiter="#######"

- name: apply bashrc assembled file
  lineinfile: dest={{ ansible_env.HOME }}/.bashrc line=". ${HOME}/.bashrc.assemble" insertafter=EOF state=present

- name: assemble all profile fragments
  assemble: src={{ role_path }}/files/.profile.d dest={{ ansible_env.HOME }}/.profile.assemble delimiter="#######"
