---
- include: "{{ common_tasks }}/deb-install.yml"
  vars:
    packages:
      - { url: "https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb", name: "slack-desktop" }    
