---
- name: add docker gpg key
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: add docker debian deb repository
  become: yes
  apt_repository: repo="deb https://apt.dockerproject.org/repo debian-jessie main" update_cache=yes state=present  
  tags: debian

- name: add docker ubuntu deb repository
  become: yes
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-xenial main" update_cache=yes state=present  
  tags: ubuntu

- name: install docker engine      
  become: yes
  apt: name=docker-engine state=latest

- name: add docker group
  become: yes
  group: name=docker system=yes state=present    

- name: add current user into docker group
  become: yes
  user: name={{ ansible_env.USER }} groups=docker append=yes state=present
  notify: restart docker    

- meta: flush_handlers

- set_fact: docker_machine_zip=docker-machine-Linux-x86_64

- name: collect information whether docker-machine is installed
  stat: path=/usr/local/bin/docker-machine  
  register: docker_machine    
  changed_when: False

- name: install docker machine
  get_url: url=https://github.com/docker/machine/releases/download/v{{ docker_machine_version }}/{{ docker_machine_zip }} dest=/usr/local/bin/docker-machine
  when: not docker_machine.stat.exists

- name: install docker-machine bash helper scripts
  become: yes
  get_url: url=https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/{{ item }}.bash dest=/etc/bash_completion.d/{{ item }} force=yes
  with_items:
    - docker-machine-prompt
    - docker-machine-wrapper
    - docker-machine

- name: install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=ug+x force=yes
