---
- name: add docker gpg key
  become: yes
  apt_key: 
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker debian deb repository
  become: yes
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" 
    filename: docker
    update_cache: yes 
    state: present
  tags: debian

- name: install docker engine      
  become: yes
  apt: 
    name: "{{ packages }}" 
    state: latest
  vars:
    packages:
    - docker-ce  
    - docker-ce-cli
    - containerd.io

- name: add docker group
  become: yes
  group: name=docker system=yes state=present    

- name: add current user into docker group
  become: yes
  user: name={{ ansible_env.USER }} groups=docker append=yes state=present
  notify: restart docker    

- meta: flush_handlers

- set_fact: docker_machine_zip=docker-machine-Linux-x86_64

- name: collect information whether docker-machine is installed
  stat: path=/usr/local/bin/docker-machine  
  register: docker_machine    
  changed_when: False

- name: install docker machine
  get_url: url=https://github.com/docker/machine/releases/download/v{{ docker_machine_version }}/{{ docker_machine_zip }} dest=/usr/local/bin/docker-machine
  when: not docker_machine.stat.exists

- name: install docker-machine bash helper scripts
  become: yes
  get_url: url=https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/{{ item }}.bash dest=/etc/bash_completion.d/{{ item }} force=yes
  with_items:
    - docker-machine-prompt
    - docker-machine-wrapper
    - docker-machine

- name: install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=ug+x force=yes
