---
- name: install Oracle JDK 1.8
  become: yes
  shell: 'wget -O - --quiet --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ jdk_url }} | tar -C /usr/lib/jvm -xzf -'
  args:
    creates: /usr/lib/jvm/jdk{{ jdk_version }}
  notify: update java version

- meta: flush_handlers
